---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pcj


**Development version: 0.0.0.9001**


```{r setup}
library(pcj)

# Default libraries.
library(grDevices)
library(graphics)
library(stats)
```


```{r}
set.seed(1L)
data = stats::rnorm(30L, mean = .7, sd = 1L)

plot(stats::density(data), main = "Data")
graphics::hist(data, add = TRUE, freq = FALSE, col = NA)
graphics::rug(data)
```


# The S3 Way

```{r}
model = pcj:::new_pcj_process_capability_model1(
  data,
  pcj::new_pci_parameters1(c("C_p", "C_pk", "C_pm"), 0, -3, 3, 1),
  "dnorm(.7, 1)T(-2, 1.5)", # JAGS syntax
  "dexp(1)T(1, 4)", # JAGS syntax
  pcj::new_prior_predictive_parameters(100L, 1L),
  pcj::new_rjags_parameters(50L, 100L, 1L, 4L, 123L, "base::Wichmann-Hill"),
  #stat = f,
  evaluate = TRUE
)
```

```{r}
if (length(get_error(model)) > 0L) {
  # ...
}

if (length(get_warning(model)) > 0L) {
  # ...
}
```


## Summarizing

```{r}
summary(model)
```

```{r}
mean(model, "posterior", "C_pm")

stats::median(model, "posterior", "C_pm")

stats::quantile(model, "posterior", "C_pm", c(.25, .5, .75))

probability(model, "posterior", "C_pm", ">= 1")
```


## Plotting

```{r fig.height = 7.5, fig.width = 6}
layout(t(matrix(1:6, 2L)))

pcj::plot_prior_density(model, what = "mu") 

pcj::plot_prior_density(model, what = "sigma")

pcj::plot_prior_predictive_density(model, what = "C_pm")

pcj::plot_posterior_density(model, what = "C_pm")

pcj::plot_prior_predictive_density(model, what = "p_nonconformance")

# Note. These functions return objects, which can be assigned to variables.
your_plot = pcj::plot_posterior_density(model, what = "p_nonconformance")
plot(your_plot)

```

## Point Priors

```{r}
model = stats::update(model, prior_mu = 1L, evaluate = TRUE)
```


```{r}
plot_prior_mass(model, what = "mu")

plot_posterior_mass(model, what = "mu", graphics = "arrows")
```


```{r}
model = stats::update(
  model, prior_mu = "dnorm(.7, 1)T(-2, 1.5)", evaluate = TRUE)
```


## The `graphics` Parameter

The `graphics` parameter can be set to `"lines"` (the default), `"points"`, or `"area"`. In case of a single point prior (like shown earlier) `"lines"` and `"arrows"` are available.

```{r}
pcj::plot_posterior_density(model, what = "C_pm")

pcj::plot_posterior_density(
  model, what = "C_pm", graphics = "area",
  x = structure(">= q.025 & <= q.975", n = 100L),
  col = grDevices::adjustcolor("black", alpha.f = .1), add = TRUE)

pcj::plot_posterior_density(
  model, what = "C_pm", graphics = "points", x = "mean", pch = 19L, 
  add = TRUE)
```

## Sequential Procedure


```{r}
seq_proc = pcj::new_pcj_sequential_procedure(model, c(20L, 25L, 30L))
```


```{r}
summary(seq_proc) |>
  get_result() |>
  subset(what == "C_pm" & distribution == "posterior")
```


```{r fig.height = 6, fig.width = 6}
pcj::plot_sequential_procedure(seq_proc, what = "C_pm", display = "ridges")
```

## Plotting Using `ggplot2`

```{r}
options(pcj.graphics_driver = "ggplot2")
```


```{r}
c(
  pcj::plot_posterior_density(model, what = "C_pm"),
  pcj::plot_posterior_density(
    model, what = "C_pm", graphics = "area",
    x = structure(">= q.025 & <= q.975", n = 100L),
    col = grDevices::adjustcolor("black", alpha.f = .1), add = TRUE
  ),
  pcj::plot_posterior_density(
    model, what = "C_pm", graphics = "points", x = c("mean"), pch = 19L, 
    add = TRUE)
)
```


```{r}
# Reset the graphics driver.
options(pcj.graphics_driver = "graphics")
```


# The R6 Way


```{r}
model = pcj::PcjProcessCapabilityModel1$new()

model$update(
  data,
  model$new_pci_parameters1(c("C_p", "C_pk", "C_pm"), 0, -3, 3, 1),
  "dnorm(.7, 1)T(-2, 1.5)",
  "dexp(1)T(1, 4)",
  model$new_prior_predictive_parameters(100L, 1L),
  model$new_rjags_parameters(50L, 100L, 1L, 4L, 123L, "base::Wichmann-Hill")
)

model$run()
```


```{r}
if (length(model$error) > 0L) {
  # ...
}

if (length(model$warning) > 0L) {
  # ...
}
```

# Summarizing

```{r}
model$summary()
```

```{r}
model$posterior$C_pm$mean()

model$posterior$C_pm$median()

model$posterior$C_pm$quantile(c(.25, .5, .75))

model$posterior$C_pm$probability(">= 1")

model$posterior$C_pm$sd()
```


```{r}
model$prior$mu$plot_density()
```

## The `stat` Parameter

```{r}
model$posterior$C_pm$plot_density(ylim = c(0., 1.))

f = function(x) {
  mu = mean(x)
  sigma = stats::sd(x)
  return(list(
    density = \(...) return(\(x) return(stats::dnorm(x, mu, sigma, FALSE))),
    quantile = \(q, ...) return(stats::qnorm(q, mu, sigma, TRUE, FALSE)),
    mean = \(...) return(mu),
    median = \(...) return(mu),
    sd = \(...) return(sigma)
  ))
}

model$update(stat = f)
model$run()

model$posterior$C_pm$plot_density(
  x = structure(">= q.001 & <= q.999", n = 1000L),
  add = TRUE, col = "steelblue", lwd = 1.5)
```


